import Vue from 'vue';
const header = () => import(/* webpackChunkName: "components" */ '../components/Header');
const footer = () => import(/* webpackChunkName: "components" */ '../components/Footer');
const Search = () => import(/* webpackChunkName: "components" */ '../components/Search');
const empty = () => import(/* webpackChunkName: "components" */ '../components/empty');
const load = () => import(/* webpackChunkName: "components" */ '../components/load');
Vue.component('Header', header);
Vue.component('Footer', footer);
Vue.component('Search', Search);
Vue.component('Empty', empty);
Vue.component('Load', load);